##
##  Makefile -- Build procedure for sample scheme Apache module
##  Autogenerated via ``apxs -n scheme -g''.
##

builddir=.
top_srcdir=/usr/local/apache2
top_builddir=/usr/local/apache2
include /usr/local/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=prelude.o
LIBS=-lchicken
shared=prelude.so

.SUFFIXES: .scm

.scm.c:
	csc -v -I$(includedir) -e -k -c $<

#   the default target
all: prelude.c local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes
	apxs -a -c -i -n scheme mod_scheme.c

#   cleanup
clean:
	rm -vf mod_scheme.o mod_scheme.lo mod_scheme.slo mod_scheme.la mod_scheme.so prelude.c prelude.o prelude.lo prelude.slo prelude.la prelude.so

#   simple test
test: reload
	lynx -mime_header http://localhost/scheme

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

